name: deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  #push:
  #  branches:
  #    - main

  pull_request:
    branches:
      - main

    paths:
      - 'docs/**'

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: testthedocs/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          BUILD_DIR: "docs/.vuepress/dist"
          BUILD_SCRIPT: yarn install && yarn docs:build
