name: deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

    paths:
      - 'docs/**'

jobs:
  build:
    name: build html
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn docs:build

  test:
    name: test links
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: linkcheck
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -d ./docs/.vuepress/dist
