name: Netlify Deploy

# only trigger on pull request closed events

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  # push:
  #   branches:
  #     - main

  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  deploy:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('yarn.lock')}}

    - name: Install
      working-directory: .
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Build
      working-directory: .
      run: yarn docs:build

    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
          args: deploy --dir=docs/.vuepress/dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
