name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://editorial.ocular-d.tech/
            https://editorial.ocular-d.tech/accessibility-terms.html
          budgetPath: ./.budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts