name: remark

on:
  push:
    paths:
    - 'docs/**'

jobs:
  build-and-test:
    name: '${{ matrix.platform }}: node.js ${{ matrix.node-version }}'
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [12, 14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn docs:lint